name: C/C++ CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: make clean
      run: make clean
    - name: make
      run: make
    - name: test xchacha
      run: ./xtest
    - name: test blake2s
      run: ./btest
    - name: test mole
      run: ./mtest
